version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-pos
    restart: unless-stopped
    environment:
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME:-sig_pos}
      - DB_USER=${DB_USER:-siguser}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST:-restaurant-db}
      - DB_PORT=${DB_PORT:-3306}
      - BACKEND_IDENTIDAD_URL=${BACKEND_IDENTIDAD_URL:-http://backend-identidad:8001}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-*}
    ports:
      - "8002:8002"
    networks:
      - restaurant-network

networks:
  restaurant-network:
    driver: bridge
    name: restaurant-network